### ISSUE TITLE
Strip leading 'v' from the version

### ISSUE THREAD

**Issue by domenkozar** [nikita-volkov/edit-cabal-version.github-action#2]
I'd like to trigger this action based on a tag like `v1.0.0`, but the github workflow expression language doesn't allow for such operation.

Maybe this action could allow stripping leading 'v'?

**Comment by domenkozar** [comment]
Another option is to use https://github.com/marketplace/actions/find-and-replace-strings

**Comment by nikita-volkov** [comment]
Does not seem to be of concern of this action.

You can do a `run` step, where you drop the `v` and produce a step output. I think that would be a more idiomatic way to do this as well.

**Comment by domenkozar** [comment]
In case someone finds it useful:

```yaml
    - name: Clean version
      uses: mad9000/actions-find-and-replace-string@1
      id: version
      with:
        source: "${{ github.ref_name }}"
        find: 'v'
        replace: ''
```
